[package]
name = "raycaster-kindle"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "raycaster-kindle"
path = "src/main.rs"

[dependencies]
raycaster-engine = { path = "../engine" }
glam = "0.28"
nix = { version = "0.29", features = ["ioctl","mman"] }
evdev = "0.12"
anyhow = "1.0"
