[package]
name = "raycaster-pc"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "raycaster-pc"
path = "src/main.rs"

[dependencies]
raycaster-engine = { path = "../engine" }
glam = "0.28"
sdl2 = { version = "0.36", features = ["mixer","image"] }
anyhow = "1.0"
